# This docker-compose file is used to start the development database.
version: "3"

services:
  postgres:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: symon
      POSTGRES_USER: symon
      POSTGRES_DB: mediapulse
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: unless-stopped
