import { createOpenAI } from "@ai-sdk/openai";
import { generateObject } from "ai";
import type { z } from "zod";

import type { ResolvedContentGenerationConfig } from "./config-schema.js";
import { formatNewsletterContent } from "./format-newsletter-content.js";
import { isRetryableLlmError } from "./llm-classify-error.js";
import { retryWithBackoff } from "./lib/retry.js";
import { truncateSources } from "./lib/truncate-sources.js";
import { newsletterStructureSchema } from "./parse-newsletter-json.js";

/** A single data source passed as input to the LLM for newsletter generation. */
export type SourceForGeneration = {
  url: string;
  title: string;
  content: string;
};

/** Structured newsletter content returned after a successful LLM call. */
export interface GeneratedContent {
  /** Compelling email subject line (under ~60 chars). */
  subject: string;
  /** Formatted plain-text newsletter body (executive summary + top 3 news). */
  content: string;
  /** Optional executive summary for newsletter preview or listing. */
  description?: string;
}

/**
 * Extended return type that additionally surfaces token usage and the exact
 * prompt strings sent to the model, needed for provenance fields (MP-CGA-008).
 */
export interface GeneratedContentWithProvenance extends GeneratedContent {
  /**
   * Number of prompt tokens consumed by the LLM call.
   * `null` when the AI SDK response does not include usage data.
   */
  promptTokens: number | null;
  /**
   * Number of completion tokens generated by the LLM call.
   * `null` when the AI SDK response does not include usage data.
   */
  completionTokens: number | null;
  /**
   * Total tokens consumed by the LLM call (`promptTokens + completionTokens`).
   * `null` when the AI SDK response does not include usage data.
   */
  totalTokens: number | null;
  /** The exact system prompt sent to the model (before any retry). */
  systemPrompt: string;
  /** The exact user prompt sent to the model after source substitution. */
  resolvedUserPrompt: string;
}

/** Minimal arguments for a single `generateObject` call for newsletter generation. */
export type GenerateNewsletterObjectArgs = {
  model: ReturnType<ReturnType<typeof createOpenAI>>;
  schema: typeof newsletterStructureSchema;
  system: string;
  prompt: string;
  /** Should always be 0 — we manage our own retry loop via retryWithBackoff. */
  maxRetries: number;
  /** Per-request timeout in milliseconds (passed to the AI SDK). */
  timeout?: number;
  /** Maximum tokens to generate (passed to `generateObject`). */
  maxTokens?: number;
};

/** Token usage extracted from a single `generateObject` response. */
export type GenerateNewsletterObjectUsage = {
  promptTokens?: number;
  completionTokens?: number;
  totalTokens?: number;
};

/** Result of a single `generateObject` call for newsletter generation. */
export type GenerateNewsletterObjectResult = {
  object: z.infer<typeof newsletterStructureSchema>;
  /**
   * Token usage from the AI SDK response.
   * Present when the model/provider returns usage data; absent otherwise.
   */
  usage?: GenerateNewsletterObjectUsage;
};

/** Injectable wrapper around `generateObject` to allow test substitution. */
export type GenerateNewsletterObjectFn = (
  args: GenerateNewsletterObjectArgs,
) => Promise<GenerateNewsletterObjectResult>;

const defaultGenerateNewsletterObject: GenerateNewsletterObjectFn = async (
  args,
) => {
  const result = await generateObject(args);
  // AI SDK v6 uses inputTokens/outputTokens (not promptTokens/completionTokens).
  // We map to the contract names (promptTokens/completionTokens/totalTokens) here
  // so the rest of the codebase speaks the contract vocabulary.
  const usage = result.usage
    ? {
        promptTokens: result.usage.inputTokens,
        completionTokens: result.usage.outputTokens,
        totalTokens:
          result.usage.inputTokens !== undefined &&
          result.usage.outputTokens !== undefined
            ? result.usage.inputTokens + result.usage.outputTokens
            : undefined,
      }
    : undefined;
  return { object: result.object, usage };
};

/**
 * System prompt sent to the LLM for newsletter generation.
 *
 * Exported so callers (e.g. `run.ts`) can compute `promptHash` from the exact
 * string passed to the model without duplicating the constant.
 */
export const SYSTEM_PROMPT = `You are a newsletter writer for busy executives. Given multiple data sources, produce a structured newsletter.

Return a JSON object with:
- "subject": a compelling email subject line (short, under ~60 chars).
- "executiveSummary": 2–3 sentences summarizing the main themes and why they matter. No bullet points; use clear prose.
- "topNews": an array of exactly {{topNewsCount}} items. Each item must have:
  - "title": short headline
  - "summaryWithLinks": 2–4 sentences that include inline markdown citations like [source](https://example.com/news)
  - "citations": array with at least one citation object, each citation has "url" and optional "label"
Use only URLs from the provided sources. Every topNews item must include at least one citation link in the summary.`;

/**
 * Default user prompt template used when no template is provided in config.
 */
export const DEFAULT_USER_PROMPT_TEMPLATE = `Create a newsletter from these data sources. Include an executive summary and the top {{topNewsCount}} news items. Each top-news summary must include inline markdown links and only use URLs from the provided sources.\n\n{{sourceSummaries}}`;

const INLINE_MARKDOWN_LINK_REGEX = /\[[^\]]+\]\((https?:\/\/[^)\s]+)\)/gi;

/**
 * Raised when generated top-news citations do not satisfy strict source-link rules.
 */
export class CitationValidationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "CitationValidationError";
  }
}

/**
 * Validates generated citations against provided source URLs and inline link usage.
 *
 * @param topNews - Generated top news items.
 * @param sourceUrls - URL set from provided source context.
 */
const validateTopNewsCitations = (
  topNews: Array<{
    title: string;
    summaryWithLinks: string;
    citations: Array<{ url: string; label?: string }>;
  }>,
  sourceUrls: ReadonlySet<string>,
): void => {
  for (const item of topNews) {
    if (item.citations.length === 0) {
      throw new CitationValidationError(
        `Missing citations for topNews item: ${item.title}`,
      );
    }
    for (const citation of item.citations) {
      if (!sourceUrls.has(citation.url)) {
        throw new CitationValidationError(
          `Citation URL not in provided sources: ${citation.url}`,
        );
      }
    }

    const inlineUrls = [
      ...item.summaryWithLinks.matchAll(INLINE_MARKDOWN_LINK_REGEX),
    ].map((match) => match[1]);
    if (inlineUrls.length === 0) {
      throw new CitationValidationError(
        `Missing inline markdown link in summaryWithLinks for: ${item.title}`,
      );
    }
    const citationUrlSet = new Set(
      item.citations.map((citation) => citation.url),
    );
    const hasMappedInlineCitation = inlineUrls.some((url) =>
      citationUrlSet.has(url),
    );
    if (!hasMappedInlineCitation) {
      throw new CitationValidationError(
        `Inline links do not match citations for: ${item.title}`,
      );
    }
  }
};

/**
 * Builds the LLM user prompt from the list of data sources, substituting
 * placeholders in the provided template.
 *
 * Supported placeholders:
 * - `{{sourceSummaries}}`: Concatenated list of article titles and content.
 * - `{{tickerId}}`: The identifier of the ticker being processed.
 * - `{{date}}`: The current ISO date (YYYY-MM-DD).
 * - `{{topNewsCount}}`: The number of top news items to generate.
 *
 * Exported so callers can compute `promptHash` from the exact string passed to
 * the model after source substitution.
 *
 * @param sources - Fetched articles/sources to include in the prompt.
 * @param template - Prompt template with placeholders (falls back to `DEFAULT_USER_PROMPT_TEMPLATE`).
 * @param context - Dynamic values for placeholder substitution.
 * @returns Formatted user-turn string for the LLM.
 */
export function buildUserPrompt(
  sources: SourceForGeneration[],
  template: string = DEFAULT_USER_PROMPT_TEMPLATE,
  context: { tickerId: string; date: string; topNewsCount: number },
): string {
  const sourceSummaries = sources
    .map(
      (source) => `Source: ${source.title} (${source.url})\n${source.content}`,
    )
    .join("\n\n---\n\n");

  return template
    .replaceAll("{{sourceSummaries}}", sourceSummaries)
    .replaceAll("{{tickerId}}", context.tickerId)
    .replaceAll("{{date}}", context.date)
    .replaceAll("{{topNewsCount}}", String(context.topNewsCount));
}

/**
 * Generates newsletter content from data sources via the Vercel AI SDK with retry logic.
 *
 * Retries on transient errors (rate limits, server errors, timeouts) up to
 * `config.llmRetry.maxAttempts` times with exponential backoff and optional jitter.
 * Non-retryable errors (auth failure, bad request, schema validation) are thrown immediately.
 *
 * Returns the generated content together with token usage and the exact prompt
 * strings sent to the model, enabling the caller to compute provenance fields
 * (`promptHash`, `promptTokens`, `completionTokens`, `totalTokens`) without
 * needing to reconstruct the prompts.
 *
 * @param sources - Fetched data sources to summarise into a newsletter.
 * @param config - Resolved agent config including `llmRetry` and `openai.timeoutMs`.
 * @param context - Dynamic values for prompt placeholder substitution (`tickerId`, `date`).
 * @param deps - Injectable dependencies: `generateObjectFn` and `sleepFn` for testing.
 * @returns Generated newsletter content plus provenance metadata.
 * @throws `APICallError` | `TypeValidationError` | `NoObjectGeneratedError` on failure.
 */
export async function generateNewsletterWithLlm(
  sources: SourceForGeneration[],
  config: ResolvedContentGenerationConfig,
  context: { tickerId: string; date: string },
  deps: {
    generateObjectFn?: GenerateNewsletterObjectFn;
    sleepFn?: (ms: number) => Promise<void>;
  } = {},
): Promise<GeneratedContentWithProvenance> {
  const generateFn = deps.generateObjectFn ?? defaultGenerateNewsletterObject;

  const topNewsCount = config.output?.topNewsCount ?? 3;

  // Truncate sources per configurable character limits before building prompts
  // (MP-CGA-004 / FR8). Sources are tail-truncated per-source, then overall
  // total is capped by dropping the least-relevant sources from the end.
  const maxCharsPerSource = config.context?.maxCharsPerSource ?? 8000;
  const maxTotalContextChars = config.context?.maxTotalContextChars ?? 100000;
  const truncatedSources = truncateSources(
    sources,
    maxCharsPerSource,
    maxTotalContextChars,
  );

  const openai = createOpenAI({
    apiKey: config.openai.apiKey,
    ...(config.openai.baseUrl ? { baseURL: config.openai.baseUrl } : {}),
  });
  const model = openai(config.openai.model);

  // Wire prompts from config with fallback to defaults (MP-CGA-003 / MP-CGA-008).
  const systemPrompt = config.prompts?.systemPrompt || SYSTEM_PROMPT;
  const userTemplate =
    config.prompts?.userPromptTemplate || DEFAULT_USER_PROMPT_TEMPLATE;
  const prompt = buildUserPrompt(truncatedSources, userTemplate, {
    tickerId: context.tickerId,
    date: context.date,
    topNewsCount,
  });

  const timeout = config.openai?.timeoutMs;
  const maxTokens = config.openai?.maxTokens;

  const sourceUrlSet = new Set(truncatedSources.map((source) => source.url));
  const result = await retryWithBackoff(
    async () => {
      const generated = await generateFn({
        model,
        schema: newsletterStructureSchema,
        system: systemPrompt,
        prompt,
        maxRetries: 0,
        ...(timeout !== undefined ? { timeout } : {}),
        ...(maxTokens !== undefined ? { maxTokens } : {}),
      });
      const topNews = Array.isArray(generated.object.topNews)
        ? generated.object.topNews.slice(0, topNewsCount)
        : [];
      validateTopNewsCitations(topNews, sourceUrlSet);
      return generated;
    },
    config.llmRetry,
    isRetryableLlmError,
    { sleepFn: deps.sleepFn },
  );

  const { object, usage } = result;
  const topNews = Array.isArray(object.topNews)
    ? object.topNews.slice(0, topNewsCount)
    : [];
  const content = formatNewsletterContent(
    object.executiveSummary ?? "",
    topNews.map((item) => ({
      title: item.title,
      summary: item.summaryWithLinks,
    })),
    topNewsCount,
  );

  return {
    subject: object.subject ?? "Your daily briefing",
    content,
    description: object.executiveSummary?.trim() || undefined,
    promptTokens: usage?.promptTokens ?? null,
    completionTokens: usage?.completionTokens ?? null,
    totalTokens: usage?.totalTokens ?? null,
    systemPrompt,
    resolvedUserPrompt: prompt,
  };
}
