import { createOpenAI } from "@ai-sdk/openai";
import { generateObject } from "ai";
import type { z } from "zod";

import type { ResolvedContentGenerationConfig } from "./config-schema.js";
import { formatNewsletterContent } from "./format-newsletter-content.js";
import { isRetryableLlmError } from "./llm-classify-error.js";
import { injectTitlePhraseLink } from "./lib/phrase-link-injector.js";
import { retryWithBackoff } from "./lib/retry.js";
import { truncateSources } from "./lib/truncate-sources.js";
import { newsletterStructureSchema } from "./parse-newsletter-json.js";

/** A single data source passed as input to the LLM for newsletter generation. */
export type SourceForGeneration = {
  url: string;
  title: string;
  content: string;
};

/** Structured newsletter content returned after a successful LLM call. */
export interface GeneratedContent {
  /** Compelling email subject line (under ~60 chars). */
  subject: string;
  /** Formatted plain-text newsletter body (executive summary + top 3 news). */
  content: string;
  /** Optional executive summary for newsletter preview or listing. */
  description?: string;
}

/**
 * Extended return type that additionally surfaces token usage and the exact
 * prompt strings sent to the model, needed for provenance fields (MP-CGA-008).
 */
export interface GeneratedContentWithProvenance extends GeneratedContent {
  /**
   * Number of prompt tokens consumed by the LLM call.
   * `null` when the AI SDK response does not include usage data.
   */
  promptTokens: number | null;
  /**
   * Number of completion tokens generated by the LLM call.
   * `null` when the AI SDK response does not include usage data.
   */
  completionTokens: number | null;
  /**
   * Total tokens consumed by the LLM call (`promptTokens + completionTokens`).
   * `null` when the AI SDK response does not include usage data.
   */
  totalTokens: number | null;
  /** The exact system prompt sent to the model (before any retry). */
  systemPrompt: string;
  /** The exact user prompt sent to the model after source substitution. */
  resolvedUserPrompt: string;
}

/** Minimal arguments for a single `generateObject` call for newsletter generation. */
export type GenerateNewsletterObjectArgs = {
  model: ReturnType<ReturnType<typeof createOpenAI>>;
  schema: typeof newsletterStructureSchema;
  system: string;
  prompt: string;
  /** Should always be 0 — we manage our own retry loop via retryWithBackoff. */
  maxRetries: number;
  /** Per-request timeout in milliseconds (passed to the AI SDK). */
  timeout?: number;
  /** Maximum tokens to generate (passed to `generateObject`). */
  maxTokens?: number;
};

/** Token usage extracted from a single `generateObject` response. */
export type GenerateNewsletterObjectUsage = {
  promptTokens?: number;
  completionTokens?: number;
  totalTokens?: number;
};

/** Result of a single `generateObject` call for newsletter generation. */
export type GenerateNewsletterObjectResult = {
  object: z.infer<typeof newsletterStructureSchema>;
  /**
   * Token usage from the AI SDK response.
   * Present when the model/provider returns usage data; absent otherwise.
   */
  usage?: GenerateNewsletterObjectUsage;
};

/** Injectable wrapper around `generateObject` to allow test substitution. */
export type GenerateNewsletterObjectFn = (
  args: GenerateNewsletterObjectArgs,
) => Promise<GenerateNewsletterObjectResult>;

const defaultGenerateNewsletterObject: GenerateNewsletterObjectFn = async (
  args,
) => {
  const result = await generateObject(args);
  // AI SDK v6 uses inputTokens/outputTokens (not promptTokens/completionTokens).
  // We map to the contract names (promptTokens/completionTokens/totalTokens) here
  // so the rest of the codebase speaks the contract vocabulary.
  const usage = result.usage
    ? {
        promptTokens: result.usage.inputTokens,
        completionTokens: result.usage.outputTokens,
        totalTokens:
          result.usage.inputTokens !== undefined &&
          result.usage.outputTokens !== undefined
            ? result.usage.inputTokens + result.usage.outputTokens
            : undefined,
      }
    : undefined;
  return { object: result.object, usage };
};

/**
 * System prompt sent to the LLM for newsletter generation.
 *
 * Exported so callers (e.g. `run.ts`) can compute `promptHash` from the exact
 * string passed to the model without duplicating the constant.
 */
export const SYSTEM_PROMPT = `You are a newsletter writer for busy executives. Given numbered article summaries, produce a structured newsletter.

Return a JSON object with:
- "subject": a compelling email subject line (short, under ~60 chars).
- "executiveSummary": 2–3 sentences summarizing the main themes and why they matter. No bullet points; use clear prose.
- "topNews": an array of exactly {{topNewsCount}} items in the same order as the numbered articles. Each item must have:
  - "title": short headline capturing the key point of that article
  - "summary": 2–4 plain sentences summarizing the article. Do not include any markdown links or citation markers.`;

/**
 * Default user prompt template used when no template is provided in config.
 */
export const DEFAULT_USER_PROMPT_TEMPLATE = `Create a newsletter from the {{topNewsCount}} articles below. Write exactly one top-news item per numbered article, in the same order.\n\n{{sourceSummaries}}`;

/**
 * Builds the LLM user prompt from the list of data sources, substituting
 * placeholders in the provided template.
 *
 * Supported placeholders:
 * - `{{sourceSummaries}}`: Numbered list of article titles and content.
 * - `{{tickerId}}`: The identifier of the ticker being processed.
 * - `{{date}}`: The current ISO date (YYYY-MM-DD).
 * - `{{topNewsCount}}`: The number of top news items to generate.
 *
 * Exported so callers can compute `promptHash` from the exact string passed to
 * the model after source substitution.
 *
 * @param sources - Fetched articles/sources to include in the prompt.
 * @param template - Prompt template with placeholders (falls back to `DEFAULT_USER_PROMPT_TEMPLATE`).
 * @param context - Dynamic values for placeholder substitution.
 * @returns Formatted user-turn string for the LLM.
 */
export function buildUserPrompt(
  sources: SourceForGeneration[],
  template: string = DEFAULT_USER_PROMPT_TEMPLATE,
  context: { tickerId: string; date: string; topNewsCount: number },
): string {
  const sourceSummaries = sources
    .map((source, i) => `Article ${i + 1}: ${source.title}\n${source.content}`)
    .join("\n\n---\n\n");

  return template
    .replaceAll("{{sourceSummaries}}", sourceSummaries)
    .replaceAll("{{tickerId}}", context.tickerId)
    .replaceAll("{{date}}", context.date)
    .replaceAll("{{topNewsCount}}", String(context.topNewsCount));
}

/**
 * Generates newsletter content from data sources via the Vercel AI SDK with retry logic.
 *
 * Selects the top `topNewsCount` sources (by relevance order from the caller) and asks
 * the LLM to write plain prose summaries — one item per article. After the LLM responds,
 * a code-based phrase-link injection step finds the phrase in each summary that best
 * matches the article title and wraps it as a markdown link, so citations are derived
 * from the source content rather than generated by the model.
 *
 * Retries on transient errors (rate limits, server errors, timeouts) up to
 * `config.llmRetry.maxAttempts` times with exponential backoff and optional jitter.
 * Non-retryable errors (auth failure, bad request, schema validation) are thrown immediately.
 *
 * Returns the generated content together with token usage and the exact prompt
 * strings sent to the model, enabling the caller to compute provenance fields
 * (`promptHash`, `promptTokens`, `completionTokens`, `totalTokens`) without
 * needing to reconstruct the prompts.
 *
 * @param sources - Fetched data sources to summarise into a newsletter.
 * @param config - Resolved agent config including `llmRetry` and `openai.timeoutMs`.
 * @param context - Dynamic values for prompt placeholder substitution (`tickerId`, `date`).
 * @param deps - Injectable dependencies: `generateObjectFn` and `sleepFn` for testing.
 * @returns Generated newsletter content plus provenance metadata.
 * @throws `APICallError` | `TypeValidationError` | `NoObjectGeneratedError` on failure.
 */
export async function generateNewsletterWithLlm(
  sources: SourceForGeneration[],
  config: ResolvedContentGenerationConfig,
  context: { tickerId: string; date: string },
  deps: {
    generateObjectFn?: GenerateNewsletterObjectFn;
    sleepFn?: (ms: number) => Promise<void>;
  } = {},
): Promise<GeneratedContentWithProvenance> {
  const generateFn = deps.generateObjectFn ?? defaultGenerateNewsletterObject;

  const topNewsCount = config.output?.topNewsCount ?? 3;

  // Truncate sources per configurable character limits before building prompts
  // (MP-CGA-004 / FR8). Sources are tail-truncated per-source, then overall
  // total is capped by dropping the least-relevant sources from the end.
  const maxCharsPerSource = config.context?.maxCharsPerSource ?? 8000;
  const maxTotalContextChars = config.context?.maxTotalContextChars ?? 100000;
  const truncatedSources = truncateSources(
    sources,
    maxCharsPerSource,
    maxTotalContextChars,
  );

  // Pre-select exactly N sources (one per news item). Sources arrive sorted by
  // relevance score from getDataSourcesForTicker; we take the top N so the LLM
  // writes one summary per article and phrase-link injection can map each item
  // back to its source URL deterministically.
  const selectedSources = truncatedSources.slice(0, topNewsCount);

  const openai = createOpenAI({
    apiKey: config.openai.apiKey,
    ...(config.openai.baseUrl ? { baseURL: config.openai.baseUrl } : {}),
  });
  const model = openai(config.openai.model);

  // Wire prompts from config with fallback to defaults (MP-CGA-003 / MP-CGA-008).
  const systemPrompt = config.prompts?.systemPrompt || SYSTEM_PROMPT;
  const userTemplate =
    config.prompts?.userPromptTemplate || DEFAULT_USER_PROMPT_TEMPLATE;
  const prompt = buildUserPrompt(selectedSources, userTemplate, {
    tickerId: context.tickerId,
    date: context.date,
    topNewsCount,
  });

  const timeout = config.openai?.timeoutMs;
  const maxTokens = config.openai?.maxTokens;

  const result = await retryWithBackoff(
    async () => {
      return generateFn({
        model,
        schema: newsletterStructureSchema,
        system: systemPrompt,
        prompt,
        maxRetries: 0,
        ...(timeout !== undefined ? { timeout } : {}),
        ...(maxTokens !== undefined ? { maxTokens } : {}),
      });
    },
    config.llmRetry,
    isRetryableLlmError,
    { sleepFn: deps.sleepFn },
  );

  const { object, usage } = result;
  const topNews = Array.isArray(object.topNews)
    ? object.topNews.slice(0, topNewsCount)
    : [];

  // Inject phrase-based markdown links into each summary. For each item at
  // index i, we find the phrase in the summary that best matches
  // selectedSources[i].title and wrap it as [phrase](url). If no phrase meets
  // the overlap threshold the summary is returned unchanged (no broken links).
  const linkedTopNews = topNews.map((item, i) => {
    const source = selectedSources[i];
    const linkedSummary =
      source !== undefined
        ? injectTitlePhraseLink(item.summary, source.title, source.url)
        : item.summary;
    return { title: item.title, summary: linkedSummary };
  });

  const content = formatNewsletterContent(
    object.executiveSummary ?? "",
    linkedTopNews,
    topNewsCount,
  );

  return {
    subject: object.subject ?? "Your daily briefing",
    content,
    description: object.executiveSummary?.trim() || undefined,
    promptTokens: usage?.promptTokens ?? null,
    completionTokens: usage?.completionTokens ?? null,
    totalTokens: usage?.totalTokens ?? null,
    systemPrompt,
    resolvedUserPrompt: prompt,
  };
}
