import { createOpenAI } from "@ai-sdk/openai";
import { generateObject } from "ai";
import type { z } from "zod";

import {
  NEWSLETTER_SECTION_IDS,
  type NewsletterSectionId,
} from "@workspace/agent-data-api-contract";
import { applyContractBrief } from "@workspace/agent-runtime";
import { formatNewsletterEmailSubject } from "@workspace/email-templates/newsletter-email-subject";
import { logger } from "@workspace/logger";

import {
  CONTENT_GENERATION_CONSTANTS,
  type ResolvedContentGenerationConfig,
} from "./config-schema.js";
import { formatIndustryNewsletterWire } from "./format-industry-newsletter.js";
import {
  industryNewsletterStructureLlmSchema,
  industryNewsletterStructureSchema,
} from "./industry-newsletter-schema.js";
import { attachIndustryNewsletterSourceUrls } from "./industry-newsletter-urls.js";
import {
  dedupeWithinRun,
  pruneNewsletterToCitedRows,
  type PruneSummary,
  type WithinRunDedupResult,
} from "./lib/prune-uncited-rows.js";
import { isRetryableLlmError } from "./llm-classify-error.js";
import {
  groundNewsletterCitations,
  type BulletGroundingReport,
  type CitationGroundingSummary,
} from "./lib/citation-grounding.js";
import { retryWithBackoff } from "./lib/retry.js";
import { truncateSources } from "./lib/truncate-sources.js";
import type { SourceForGeneration } from "./types.js";

export type { SourceForGeneration };

/** Per-section bullet and removal counts from the final resolved newsletter. */
export type SectionFillSnapshot = {
  bySection: Record<NewsletterSectionId, { citedBullets: number }>;
  sectionsRemoved: NewsletterSectionId[];
};

/**
 * Counts cited bullets shipped per newsletter section from the final resolved structure.
 * Prose sections (`industryPulse`, `disruptorsOrTech` when format=prose) count as 1 item each.
 * Sections absent in the resolved structure contribute 0.
 *
 * @param resolved - Final resolved newsletter after all pruning passes.
 * @returns Per-section bullet counts.
 */
export const computeNewsletterSectionFill = (
  resolved: import("./industry-newsletter-urls.js").IndustryNewsletterResolved,
): Record<NewsletterSectionId, { citedBullets: number }> => {
  const disruptorsOrTechCount =
    resolved.disruptorsOrTech === undefined
      ? 0
      : resolved.disruptorsOrTech.format === "bullets"
        ? resolved.disruptorsOrTech.bullets.length
        : 1;

  return Object.fromEntries(
    NEWSLETTER_SECTION_IDS.map((id) => {
      let citedBullets: number;
      if (id === "industryPulse") {
        citedBullets = resolved.industryPulse !== undefined ? 1 : 0;
      } else if (id === "competitiveLandscape") {
        citedBullets = resolved.competitiveLandscape?.bullets.length ?? 0;
      } else if (id === "dealsAndMovements") {
        citedBullets = resolved.dealsAndMovements?.bullets.length ?? 0;
      } else if (id === "regulatoryPolicyWatch") {
        citedBullets = resolved.regulatoryPolicyWatch?.bullets.length ?? 0;
      } else if (id === "disruptorsOrTech") {
        citedBullets = disruptorsOrTechCount;
      } else {
        citedBullets = resolved.quickHits?.items.length ?? 0;
      }

      return [id, { citedBullets }];
    }),
  ) as Record<NewsletterSectionId, { citedBullets: number }>;
};

/** Structured newsletter content returned after a successful LLM call. */
export interface GeneratedContent {
  /** Compelling email subject line (under ~60 chars). */
  subject: string;
  /** Formatted plain-text newsletter body (`MP_NEWSLETTER` industry wire). */
  content: string;
  /** Optional executive summary for newsletter preview or listing. */
  description?: string;
}

/**
 * Extended return type that additionally surfaces token usage and the exact
 * prompt strings sent to the model, needed for provenance fields (MP-CGA-008).
 */
export interface GeneratedContentWithProvenance extends GeneratedContent {
  /**
   * Number of prompt tokens consumed by the LLM call.
   * `null` when the AI SDK response does not include usage data.
   */
  promptTokens: number | null;
  /**
   * Number of completion tokens generated by the LLM call.
   * `null` when the AI SDK response does not include usage data.
   */
  completionTokens: number | null;
  /**
   * Total tokens consumed by the LLM call (`promptTokens + completionTokens`).
   * `null` when the AI SDK response does not include usage data.
   */
  totalTokens: number | null;
  /** The exact system prompt sent to the model (before any retry). */
  systemPrompt: string;
  /** The exact user prompt sent to the model after source substitution. */
  resolvedUserPrompt: string;
  /**
   * Reasoning tokens consumed by the structured pass.
   * Present only when the model reports them (gpt-5/o-series with reasoning effort set).
   */
  structuredReasoningTokens?: number;
  /** Per-bullet grounding reports from the citation safety net. */
  citationGroundingReports?: BulletGroundingReport[];
  /** Rolled-up citation grounding counters for run details. */
  citationGroundingSummary?: CitationGroundingSummary;
  /** Require-citation pruning counters from the final transform. */
  requireCitationSummary?: PruneSummary;
  /** Per-section bullet counts and removed-section list from the final resolved newsletter. */
  sectionFillSnapshot?: SectionFillSnapshot;
}

/** Minimal arguments for a single `generateObject` call for newsletter generation. */
export type GenerateNewsletterObjectArgs = {
  model: ReturnType<ReturnType<typeof createOpenAI>>;
  schema: typeof industryNewsletterStructureLlmSchema;
  system: string;
  prompt: string;
  /** Should always be 0 — we manage our own retry loop via retryWithBackoff. */
  maxRetries: number;
  /** Per-request timeout in milliseconds (passed to the AI SDK). */
  timeout?: number;
};

/** Token usage extracted from a single `generateObject` response. */
export type GenerateNewsletterObjectUsage = {
  promptTokens?: number;
  completionTokens?: number;
  totalTokens?: number;
  reasoningTokens?: number;
};

/** Result of a single `generateObject` call for newsletter generation. */
export type GenerateNewsletterObjectResult = {
  object: z.infer<typeof industryNewsletterStructureSchema>;
  /**
   * Token usage from the AI SDK response.
   * Present when the model/provider returns usage data; absent otherwise.
   */
  usage?: GenerateNewsletterObjectUsage;
};

/** Injectable wrapper around `generateObject` to allow test substitution. */
export type GenerateNewsletterObjectFn = (
  args: GenerateNewsletterObjectArgs,
) => Promise<GenerateNewsletterObjectResult>;

const defaultGenerateNewsletterObject: GenerateNewsletterObjectFn = async (
  args,
) => {
  const result = await generateObject({
    ...args,
  });
  // AI SDK v6 uses inputTokens/outputTokens (not promptTokens/completionTokens).
  // We map to the contract names (promptTokens/completionTokens/totalTokens) here
  // so the rest of the codebase speaks the contract vocabulary.
  const usage = result.usage
    ? {
        promptTokens: result.usage.inputTokens,
        completionTokens: result.usage.outputTokens,
        totalTokens:
          result.usage.inputTokens !== undefined &&
          result.usage.outputTokens !== undefined
            ? result.usage.inputTokens + result.usage.outputTokens
            : undefined,
        // reasoningTokens is present on reasoning models (gpt-5/o-series).
        ...(result.usage.reasoningTokens !== undefined
          ? { reasoningTokens: result.usage.reasoningTokens }
          : {}),
      }
    : undefined;
  return { object: result.object, usage };
};

/**
 * Builds the numbered `Article N:` block. Each article carries its authoritative
 * upstream `Assigned section`, which the LLM must honour rather than re-classify.
 *
 * @param sources - Sources in prompt order (already grouped by section).
 * @returns Joined article summaries.
 */
export const buildArticleSummariesBlock = (
  sources: readonly SourceForGeneration[],
): string => {
  return sources
    .map((source, index) => {
      const sectionLine = source.section
        ? `\nAssigned section: ${source.section}`
        : "";
      return `Article ${String(index + 1)}: ${source.title}${sectionLine}\n${source.content}`;
    })
    .join("\n\n---\n\n");
};

/**
 * Orders sources by their authoritative upstream `section` so the prompt presents
 * articles grouped section-by-section. Ordering within a section and the relative
 * order of sources is otherwise preserved (stable sort).
 *
 * @param sources - Sources to group.
 * @returns Sources reordered so that articles sharing a section are contiguous.
 */
export const groupSourcesBySection = (
  sources: readonly SourceForGeneration[],
): SourceForGeneration[] => {
  const sectionOrder = new Map<string, number>(
    NEWSLETTER_SECTION_IDS.map((id, index) => [id, index]),
  );
  const rankOf = (source: SourceForGeneration): number => {
    if (source.section === undefined || source.section === null) {
      return NEWSLETTER_SECTION_IDS.length;
    }
    return sectionOrder.get(source.section) ?? NEWSLETTER_SECTION_IDS.length;
  };

  return sources
    .map((source, index) => ({ source, index }))
    .sort((a, b) => {
      const rankDiff = rankOf(a.source) - rankOf(b.source);
      if (rankDiff !== 0) {
        return rankDiff;
      }

      return a.index - b.index;
    })
    .map((entry) => entry.source);
};

/**
 * System prompt sent to the LLM for newsletter generation.
 *
 * Exported so callers (e.g. `run.ts`) can compute `promptHash` from the exact
 * string passed to the model without duplicating the constant.
 *
 * Supported placeholders: `{{topNewsCount}}`, `{{tickerId}}`, `{{tickerName}}`, `{{tickerSymbol}}`.
 */
export const SYSTEM_PROMPT = `You are an industry intelligence editor for busy business owners and executives.

Audience: leaders who want sector context, competition, regulation, and deals — not stock tips. Never give buy/sell/hold guidance, price targets, or personal investment advice.

Use {{tickerName}} ({{tickerSymbol}}) to orient the industry intelligence lens. Do not make every paragraph only about that single ticker; widen to industry dynamics when the articles support it.

Focus on what is happening outside the company — macro forces, regulatory shifts, competitive moves, technology disruption. Do not include earnings guidance, internal financial projections, or company-specific forecast commentary.

You receive exactly {{topNewsCount}} numbered articles (Article 1 … Article {{topNewsCount}}). Ground claims in those articles. When a bullet or quick hit should link to a source in the final email, set "articleIndex" to the 1-based article number from that list. Never output URLs in JSON; the system injects them. Never write "(Article N)", "(cited Article N)", "(see Article N)", or bare article numbers inside any "text" or "prose" field; citations are expressed only via "articleIndex", and the system renders the visible link.

Return JSON matching this shape (camelCase keys):
- "subject": short email subject title only (under ~48 chars), sector-relevant headline text. Do not include a "SYMBOL Pulse:" prefix — the system adds that automatically. Avoid repeating {{tickerSymbol}} in the title when the prefix already identifies the ticker.
- "industryPulse": { "displayHeading", "prose", "articleIndex" } — short lead framing the industry story (no bullet characters in prose). Set "articleIndex" to the single most representative article the lead summarizes; use null when the lead does not lean on a specific article.
- "competitiveLandscape": { "displayHeading", "bullets" } — 2–3 bullets about {{tickerName}}'s COMPETITORS, not {{tickerName}} itself — peer positioning, rival launches, share shifts, competitive threats. Each bullet should name a competitor. Each bullet { "title", "text", "articleIndex" } where "title" is a short headline (under 60 chars) naming the story, "text" is the full bullet sentence, and articleIndex is a 1-based article number or null when uncited.
- "dealsAndMovements": { "displayHeading", "bullets" } — 1–3 bullets; each bullet { "title", "text", "articleIndex" } with the same title and articleIndex rules.
- "regulatoryPolicyWatch": { "displayHeading", "bullets" } — 1–3 bullets; same title and articleIndex rules.
- "disruptorsOrTech": either { "format": "prose", "displayHeading", "prose" } OR { "format": "bullets", "displayHeading", "bullets" } with 1–3 bullets (each bullet has "title", "text", "articleIndex" with the same rules).
- "quickHits": { "displayHeading", "items" } — 5–7 items; each item { "title", "text", "articleIndex" } where "title" is a short headline (under 60 chars), "text" is the sentence, and articleIndex is required.

Headings ("displayHeading") are short subtitle phrases only — never repeat the section label or use "Label / Subtitle" format. Keep JSON valid; use null for optional blocks and uncited articleIndex values.

Each article lists an "Assigned section". That assignment is authoritative — place that article in the named section (industryPulse, competitiveLandscape, dealsAndMovements, regulatoryPolicyWatch, disruptorsOrTech, or quickHits). Only fall back to your own judgement for articles with no assigned section.

Every bullet and quick hit must summarize exactly one article and set articleIndex to that one article. Do not blend multiple articles into one bullet, and do not reuse the same article for two bullets in a section.

Item titles must be unique across the entire newsletter (all bullets in all sections and all quick-hit items). Every title must name a distinct story. Do not reuse the same headline or a near-identical paraphrase for two different items.

Cross-section duplication is forbidden. Do not cover the same story in two different sections, even from different angles. Do not write two items about the same event in different sections. Each article (by articleIndex) may be cited at most once across the entire newsletter — if an article is used in one section, it must not appear in any other section or in quickHits.`;

/**
 * Default user prompt template.
 */
export const DEFAULT_USER_PROMPT_TEMPLATE = `Today is {{date}}. Use that date to vary emphasis week to week (for example alternate between global macro vs regional industry notes) without inventing facts.

Write one JSON industry briefing using the {{topNewsCount}} numbered articles below. Follow the system JSON shape exactly.

Rules reminder:
- Industry and competitive lens; no trading advice.
- Use "articleIndex" to point at Article 1 … Article {{topNewsCount}} from this prompt. Set articleIndex to null on a bullet when there is no clear single-article grounding.
- Quick hits must all include articleIndex.

{{sourceSummaries}}`;

/**
 * Builds the competitor directive block injected into the user prompt when
 * the KG has resolved named competitors for the issuer.
 *
 * Returns an empty string when `competitors` is empty, so the caller can
 * safely include it without an extra length guard.
 *
 * @param competitors - Named competitors from the KG resolution pass.
 * @param issuerName - Human-readable issuer name for the directive text.
 */
export const buildCompetitorPromptBlock = (
  competitors: ReadonlyArray<{ name: string; relation: string }>,
  issuerName: string,
): string => {
  if (competitors.length === 0) return "";
  const nameList = competitors.map((competitor) => competitor.name).join(", ");
  return [
    `Competitive Landscape must focus on these competitors of ${issuerName}: ${nameList}.`,
    `Frame each bullet around a competitor's move, market share shift, product launch, or competitive threat.`,
    `Do NOT make these bullets about ${issuerName} itself.`,
  ].join(" ");
};

/**
 * Builds the LLM user prompt from the list of data sources, substituting
 * placeholders in the provided template.
 *
 * Supported placeholders:
 * - `{{sourceSummaries}}`: Numbered list of article titles and content.
 * - `{{tickerId}}`: The identifier of the ticker being processed.
 * - `{{tickerName}}`: The human-readable company name (e.g. "Bank Central Asia").
 * - `{{tickerSymbol}}`: The exchange ticker symbol (e.g. "BBCA").
 * - `{{date}}`: The current ISO date (YYYY-MM-DD).
 * - `{{topNewsCount}}`: The number of articles included in this prompt (and max articleIndex).
 *
 * Exported so callers can compute `promptHash` from the exact string passed to
 * the model after source substitution.
 *
 * @param sources - Fetched articles/sources to include in the prompt (pre-grouped by section).
 * @param template - Prompt template with placeholders (falls back to `DEFAULT_USER_PROMPT_TEMPLATE`).
 * @param context - Dynamic values for placeholder substitution.
 * @param options - Optional competitor directive injected above article summaries.
 * @returns Formatted user-turn string for the LLM.
 */
export function buildUserPrompt(
  sources: SourceForGeneration[],
  template: string = DEFAULT_USER_PROMPT_TEMPLATE,
  context: {
    tickerId: string;
    date: string;
    topNewsCount: number;
    tickerName?: string;
    tickerSymbol?: string;
  },
  options: {
    /** Competitor directive injected above article summaries when the KG has named peers. */
    competitorSection?: string;
  } = {},
): string {
  const sourceSummaries = buildArticleSummariesBlock(sources);

  const competitorPrefix =
    options.competitorSection !== undefined &&
    options.competitorSection.length > 0
      ? `${options.competitorSection}\n\n`
      : "";

  return template
    .replaceAll("{{sourceSummaries}}", `${competitorPrefix}${sourceSummaries}`)
    .replaceAll("{{tickerId}}", context.tickerId)
    .replaceAll("{{tickerName}}", context.tickerName ?? context.tickerId)
    .replaceAll("{{tickerSymbol}}", context.tickerSymbol ?? context.tickerId)
    .replaceAll("{{date}}", context.date)
    .replaceAll("{{topNewsCount}}", String(context.topNewsCount));
}

/**
 * Generates newsletter content from already-sectioned data sources via the
 * Vercel AI SDK with retry logic.
 *
 * Pipeline: truncate sources to the hardcoded context budgets, group them by
 * their authoritative upstream `section`, run a single structured `generateObject`
 * call (wrapped in `retryWithBackoff`), apply the always-on citation safety net
 * (grounding + require-citation prune), attach source URLs, and serialize to the
 * `MP_NEWSLETTER` plain-text wire format. The model's own subject is used.
 *
 * Returns the generated content together with token usage and the exact prompt
 * strings sent to the model, enabling the caller to compute provenance fields.
 *
 * @param sources - Fetched data sources to summarise into a newsletter.
 * @param config - Resolved agent config (only the model block is read).
 * @param context - Dynamic values for prompt placeholder substitution and light KG context.
 * @param deps - Injectable dependencies: `generateObjectFn` and `sleepFn` for testing.
 * @returns Generated newsletter content plus provenance metadata.
 * @throws `APICallError` | `TypeValidationError` | `NoObjectGeneratedError` on failure.
 */
export async function generateNewsletterWithLlm(
  sources: SourceForGeneration[],
  config: ResolvedContentGenerationConfig,
  context: {
    tickerId: string;
    date: string;
    tickerName?: string;
    tickerSymbol?: string;
    /** KG-resolved competitor list from the content-generation API. */
    competitors?: Array<{ name: string; relation: string }>;
    /** Issuer aliases from the content-generation API. */
    issuerAliases?: string[];
    /** Opaque product brief from the Agent Contract; appended to the system prompt when present. */
    brief?: string;
  },
  deps: {
    generateObjectFn?: GenerateNewsletterObjectFn;
    sleepFn?: (ms: number) => Promise<void>;
  } = {},
): Promise<GeneratedContentWithProvenance> {
  const generateFn = deps.generateObjectFn ?? defaultGenerateNewsletterObject;

  const { topNewsCount, requestTimeoutMs, truncation, retry } =
    CONTENT_GENERATION_CONSTANTS;

  // Truncate sources per hardcoded character limits before building prompts.
  // Sources are tail-truncated per-source, then the overall total is capped by
  // dropping the least-relevant sources from the end.
  const truncatedSources = truncateSources(
    sources,
    truncation.maxCharsPerSource,
    truncation.maxTotalContextChars,
  );

  // Pre-select up to N sources for the prompt, then group them by their
  // authoritative upstream section so the prompt presents articles section-by-section.
  const selectedSources = truncatedSources.slice(0, topNewsCount);
  const promptSources = groupSourcesBySection(selectedSources);
  const effectiveTopNewsCount = promptSources.length;

  const openai = createOpenAI({
    apiKey: config.model.apiKey,
    ...(config.model.baseUrl ? { baseURL: config.model.baseUrl } : {}),
  });
  const model = openai(config.model.model);

  // Apply placeholder substitution to the system prompt so {{topNewsCount}},
  // {{tickerName}}, and {{tickerSymbol}} are resolved before the LLM call.
  const substitutedSystemPrompt = SYSTEM_PROMPT.replaceAll(
    "{{topNewsCount}}",
    String(effectiveTopNewsCount),
  )
    .replaceAll("{{tickerId}}", context.tickerId)
    .replaceAll("{{tickerName}}", context.tickerName ?? context.tickerId)
    .replaceAll("{{tickerSymbol}}", context.tickerSymbol ?? context.tickerId);
  const systemPrompt = applyContractBrief(
    substitutedSystemPrompt,
    context.brief !== undefined ? { brief: context.brief } : undefined,
  );

  const promptCompetitors = context.competitors ?? [];
  const competitorSection = buildCompetitorPromptBlock(
    promptCompetitors,
    context.tickerName ?? context.tickerId,
  );

  const prompt = buildUserPrompt(
    promptSources,
    DEFAULT_USER_PROMPT_TEMPLATE,
    {
      tickerId: context.tickerId,
      date: context.date,
      topNewsCount: effectiveTopNewsCount,
      tickerName: context.tickerName,
      tickerSymbol: context.tickerSymbol,
    },
    { competitorSection },
  );

  const result = await retryWithBackoff(
    async () => {
      return generateFn({
        model,
        schema: industryNewsletterStructureLlmSchema,
        system: systemPrompt,
        prompt,
        maxRetries: 0,
        timeout: requestTimeoutMs,
      });
    },
    retry,
    isRetryableLlmError,
    { sleepFn: deps.sleepFn },
  );

  const { object: finalStructure, usage } = result;

  // -------------------------------------------------------------------------
  // Citation safety net (always on)
  // -------------------------------------------------------------------------
  const grounding = CONTENT_GENERATION_CONSTANTS.citationGrounding;
  const grounded = groundNewsletterCitations(finalStructure, promptSources, {
    policy: grounding.policy,
    minOverlapScore: grounding.minOverlapScore,
    numericBonus: grounding.numericBonus,
  });
  const citationGroundingReports = grounded.reports;
  const citationGroundingSummary = grounded.summary;

  if (grounded.quickHitsKeptDespiteFailedGrounding > 0) {
    logger.warn(
      {
        tickerId: context.tickerId,
        keptCount: grounded.quickHitsKeptDespiteFailedGrounding,
        event: "quickHits_ground_failed_keeping_item",
      },
      "Quick hits below grounding threshold kept to satisfy schema minimum",
    );
  }

  logger.info(
    {
      tickerId: context.tickerId,
      groundingPolicy: grounding.policy,
      totalCitations: grounded.summary.totalCitations,
      unlinked: grounded.summary.unlinked,
      dropped: grounded.summary.dropped,
      floorPreserved: grounded.summary.floorPreserved,
      p50Overlap: grounded.summary.p50Overlap,
      p10Overlap: grounded.summary.p10Overlap,
    },
    "Citation grounding summary",
  );

  let resolved = attachIndustryNewsletterSourceUrls(
    grounded.structure,
    promptSources,
  );

  const requireCitation = CONTENT_GENERATION_CONSTANTS.requireCitation;
  const pruned = pruneNewsletterToCitedRows(resolved, {
    sections: requireCitation.sections,
    dedupeArticlesWithinSection: requireCitation.dedupeArticlesWithinSection,
    dedupeScope: requireCitation.dedupeScope,
  });
  resolved = pruned.resolved;
  const requireCitationSummary = pruned.summary;
  const prunedSectionsRemoved: NewsletterSectionId[] = pruned.reports
    .filter((report) => report.sectionRemoved)
    .map((report) => report.sectionKey as NewsletterSectionId);

  logger.info(
    {
      tickerId: context.tickerId,
      sectionsRemoved: pruned.summary.sectionsRemoved,
      bulletsRemovedUncited: pruned.summary.bulletsRemovedUncited,
      bulletsRemovedDuplicate: pruned.summary.bulletsRemovedDuplicate,
      sectionsKept: pruned.summary.sectionsKept,
    },
    "Require-citation pruning summary",
  );

  const withinRunDeduped: WithinRunDedupResult = dedupeWithinRun(
    resolved,
    requireCitation.withinRunDedupSimilarity,
  );
  resolved = withinRunDeduped.resolved;

  if (withinRunDeduped.removedCount > 0) {
    logger.info(
      {
        tickerId: context.tickerId,
        removedCount: withinRunDeduped.removedCount,
        minSimilarity: requireCitation.withinRunDedupSimilarity,
        event: "within_run_semantic_dedup",
      },
      `Within-run semantic dedup: removed ${String(withinRunDeduped.removedCount)} near-duplicate item(s)`,
    );
  }

  const content = formatIndustryNewsletterWire(resolved);

  const rawTitle =
    finalStructure.subject.trim().length > 0
      ? finalStructure.subject.trim()
      : "Your daily briefing";
  const subject = formatNewsletterEmailSubject(
    context.tickerSymbol ?? "",
    rawTitle,
  );

  return {
    subject,
    content,
    // Reads the pre-prune finalStructure, so this is safe even when the resolved
    // lead was later removed by the require-citation pass.
    description: finalStructure.industryPulse.prose.trim() || undefined,
    promptTokens: usage?.promptTokens ?? null,
    completionTokens: usage?.completionTokens ?? null,
    totalTokens: usage?.totalTokens ?? null,
    systemPrompt,
    resolvedUserPrompt: prompt,
    ...(usage?.reasoningTokens !== undefined
      ? { structuredReasoningTokens: usage.reasoningTokens }
      : {}),
    citationGroundingReports,
    citationGroundingSummary,
    requireCitationSummary,
    sectionFillSnapshot: {
      bySection: computeNewsletterSectionFill(resolved),
      sectionsRemoved: prunedSectionsRemoved,
    },
  };
}
