import type { DashboardViewInput } from "@hermes/domain-contract";
import { hermesDashboardManifestApiPrefix } from "../../hermes-dashboard/hermes-dashboard-path-helpers";
import {
  createdAtDateRangeListFilter,
  intentSelectListFilter,
  isActiveBooleanSelectListFilter,
  tickerIdSelectListFilter,
} from "../../hermes-dashboard/templates/table-v1/list-filter-definitions";
import {
  columnsFor,
  rowFieldKeysFor,
  yesNoBadgeTones,
} from "../../hermes-dashboard/templates/table-v1/manifest-field-helpers";
import type { ListItem } from "./list-mapper";
import { searchQueriesCustomActionsForManifest } from "./custom-actions";

export const searchQueriesHermesPathSegment = "search-queries" as const;

export const searchQueriesDashboardPage = {
  id: searchQueriesHermesPathSegment,
  label: "Search Queries",
  description:
    "Individual search queries generated by the query-analysis agent. Delete unused rows or reset all.",
  pathSegment: searchQueriesHermesPathSegment,
  kind: "resource-table" as const,
  placement: "sidebar" as const,
  apiPrefix: hermesDashboardManifestApiPrefix(searchQueriesHermesPathSegment),
  order: 40,
  columns: columnsFor<ListItem>()([
    { key: "tickerSymbol", label: "Ticker", type: "text" },
    { key: "text", label: "Search query", type: "text", mobile: "subtitle" },
    {
      key: "activeSet",
      label: "Active set",
      type: "text",
      format: "badge",
      badgeTones: yesNoBadgeTones,
      mobile: "badge",
    },
    { key: "intent", label: "Intent", type: "text" },
    { key: "rank", label: "Rank", type: "text", format: "number" },
    {
      key: "createdAt",
      label: "Created",
      type: "date-time",
      format: "date-time",
    },
  ]),
  searchableFields: rowFieldKeysFor<ListItem>()([
    "tickerSymbol",
    "text",
    "intent",
  ]),
  sortableFields: rowFieldKeysFor<ListItem>()([
    "createdAt",
    "rank",
    "activeSet",
  ]),
  listFilters: [
    tickerIdSelectListFilter,
    isActiveBooleanSelectListFilter,
    intentSelectListFilter,
    createdAtDateRangeListFilter,
  ],
  actions: { create: false, update: false, delete: true, view: false },
  customActions: searchQueriesCustomActionsForManifest,
} satisfies DashboardViewInput;
