/**
 * Hermes `table-v1` manifest for search queries (delete-only actions) and exported path segment.
 */

import type { DashboardPageInput } from "@hermes/domain-contract";
import { hermesDashboardManifestApiPrefix } from "../../hermes-dashboard/hermes-dashboard-path-helpers";
import {
  columnsFor,
  rowFieldKeysFor,
} from "../../hermes-dashboard/templates/table-v1/manifest-field-helpers";
import type { ListItem } from "./list-mapper";
import { searchQueriesCustomActionsForManifest } from "./custom-actions";

/** URL path segment for this resource under `/v1/hermes-dashboard/`. */
export const searchQueriesHermesPathSegment = "search-queries" as const;

/** Hermes `table-v1` manifest page for search queries. */
export const searchQueriesDashboardPage = {
  id: searchQueriesHermesPathSegment,
  label: "Search Queries",
  description:
    "Individual search queries generated by the query-analysis agent. Delete unused rows or reset all.",
  pathSegment: searchQueriesHermesPathSegment,
  template: "table-v1" as const,
  apiPrefix: hermesDashboardManifestApiPrefix(searchQueriesHermesPathSegment),
  order: 40,
  columns: columnsFor<ListItem>()([
    { key: "tickerSymbol", label: "Ticker", type: "text" },
    { key: "tickerName", label: "Ticker Name", type: "text" },
    { key: "text", label: "Search Query", type: "text" },
    { key: "activeSet", label: "Active set", type: "text" },
    { key: "intent", label: "Intent", type: "text" },
    { key: "rank", label: "Rank", type: "text" },
    { key: "source", label: "Source", type: "text" },
    { key: "setGeneratedAt", label: "Set generated", type: "date-time" },
    { key: "generationPipeline", label: "Generation pipeline", type: "text" },
    { key: "querySetId", label: "Query set id", type: "text" },
    { key: "agentJobId", label: "Hermes job id", type: "text" },
    { key: "createdAt", label: "Created", type: "date-time" },
    { key: "updatedAt", label: "Updated", type: "date-time" },
  ]),
  searchableFields: rowFieldKeysFor<ListItem>()([
    "tickerName",
    "tickerSymbol",
    "text",
    "intent",
    "source",
    "querySetId",
    "agentJobId",
  ]),
  sortableFields: rowFieldKeysFor<ListItem>()([
    "createdAt",
    "updatedAt",
    "setGeneratedAt",
    "rank",
    "activeSet",
  ]),
  listFilters: ["tickerId", "isActive", "intent", "source", "createdAt"],
  actions: { create: false, update: false, delete: true, view: false },
  customActions: searchQueriesCustomActionsForManifest,
} satisfies DashboardPageInput;
