/**
 * Pure helpers shared by the Prisma write-field metadata codegen script and its unit tests.
 *
 * The set of Prisma models that appear in the generated metadata file is **not** inferred from the
 * whole schema: see {@link PRISMA_WRITE_METADATA_MODEL_NAMES}.
 */

/**
 * **Allowlist** of Prisma model names whose scalar/enum fields are emitted into
 * `src/generated/prisma-write-field-metadata.ts`.
 *
 * - Other models in `packages/mediapulse/database/prisma/schema.prisma` are ignored by this codegen.
 * - When you add a new Hermes `table-v1` resource backed by a model that is not listed here, append
 *   the model name, run `pnpm --filter @mediapulse/domain-api generate`, then add `write-body-schemas.ts`
 *   (and routes/dashboard) for that resource.
 */
export const PRISMA_WRITE_METADATA_MODEL_NAMES = [
  "CuratedSource",
  "EntityType",
  "RelationType",
  "MediapulseUser",
  "Ticker",
] as const;

export type PrismaWriteMetadataModelName =
  (typeof PRISMA_WRITE_METADATA_MODEL_NAMES)[number];

export type ScalarFieldMeta = {
  kind: "scalar";
  type: string;
  isRequired: boolean;
  isList: boolean;
};

export type EnumFieldMeta = {
  kind: "enum";
  enumName: string;
  isRequired: boolean;
  isList: boolean;
};

export type FieldMeta = ScalarFieldMeta | EnumFieldMeta;

/**
 * Maps a DMMF datamodel field to compact metadata used for Zod generation, or `null` for relations / unsupported kinds.
 *
 * @param field - Field object from Prisma `get_dmmf` datamodel JSON.
 * @returns Scalar/enum metadata, or `null` when the field should not appear in write schemas.
 */
export const dmmfFieldToWriteMeta = (field: {
  kind: string;
  name: string;
  type: string;
  isRequired: boolean;
  isList: boolean;
}): FieldMeta | null => {
  if (field.kind === "scalar") {
    return {
      kind: "scalar",
      type: field.type,
      isRequired: field.isRequired,
      isList: field.isList,
    };
  }
  if (field.kind === "enum") {
    return {
      kind: "enum",
      enumName: field.type,
      isRequired: field.isRequired,
      isList: field.isList,
    };
  }
  return null;
};

/**
 * Renders the generated `prisma-write-field-metadata.ts` module source.
 *
 * @param models - Map of Prisma model name to field metadata records.
 * @returns Full file contents including header comment and exported types.
 */
export const formatPrismaWriteFieldMetadataModule = (
  models: Record<PrismaWriteMetadataModelName, Record<string, FieldMeta>>,
): string => {
  const serialized = JSON.stringify(models, null, 2);
  return `/**
 * Generated by scripts/generate-prisma-write-field-metadata.ts — do not edit.
 * Re-run: pnpm --filter @mediapulse/domain-api generate:prisma-write-field-metadata
 */

export type PrismaWriteScalarFieldMeta = {
  kind: "scalar";
  type: string;
  isRequired: boolean;
  isList: boolean;
};

export type PrismaWriteEnumFieldMeta = {
  kind: "enum";
  enumName: string;
  isRequired: boolean;
  isList: boolean;
};

export type PrismaWriteFieldMeta = PrismaWriteScalarFieldMeta | PrismaWriteEnumFieldMeta;

export type PrismaWriteFieldMetadata = typeof prismaWriteFieldMetadata;

export const prismaWriteFieldMetadata = ${serialized} as const satisfies Record<
  string,
  Record<string, PrismaWriteFieldMeta>
>;
`;
};
