/** @vitest-environment node */
import { describe, expect, it } from "vitest";

import {
  dmmfFieldToWriteMeta,
  formatPrismaWriteFieldMetadataModule,
} from "./prisma-write-metadata-codegen-helpers";

describe("dmmfFieldToWriteMeta", () => {
  it("maps scalar fields", () => {
    // Act
    const meta = dmmfFieldToWriteMeta({
      kind: "scalar",
      name: "title",
      type: "String",
      isRequired: true,
      isList: false,
    });

    // Assert
    expect(meta).toEqual({
      kind: "scalar",
      type: "String",
      isRequired: true,
      isList: false,
    });
  });

  it("maps enum fields", () => {
    // Act
    const meta = dmmfFieldToWriteMeta({
      kind: "enum",
      name: "status",
      type: "OrderStatus",
      isRequired: false,
      isList: false,
    });

    // Assert
    expect(meta).toEqual({
      kind: "enum",
      enumName: "OrderStatus",
      isRequired: false,
      isList: false,
    });
  });

  it("returns null for object fields", () => {
    // Act
    const meta = dmmfFieldToWriteMeta({
      kind: "object",
      name: "user",
      type: "User",
      isRequired: true,
      isList: false,
    });

    // Assert
    expect(meta).toBeNull();
  });
});

describe("formatPrismaWriteFieldMetadataModule", () => {
  it("renders a valid module header and JSON body", () => {
    // Setup — one model is enough to assert formatting; cast avoids duplicating all configured models.
    const models = {
      EntityType: {
        name: {
          kind: "scalar" as const,
          type: "String",
          isRequired: true,
          isList: false,
        },
      },
    };

    // Act
    const src = formatPrismaWriteFieldMetadataModule(
      // Test-only partial: formatter only stringifies the object shape.
      models as never,
    );

    // Assert
    expect(src).toContain(
      "Generated by scripts/generate-prisma-write-field-metadata.ts",
    );
    expect(src).toContain('"EntityType"');
    expect(src).toContain('"name"');
  });
});
