import { prisma as mediapulsePrisma } from "@mediapulse/database";
import type { Prisma } from "@mediapulse/database";

/** Outcome filter values aligned with {@link ContentGenerationRunOutcome}. */
export type ContentGenerationRunOutcomeFilter =
  | "success"
  | "skipped"
  | "failed";

/** Stage filter values aligned with {@link ContentGenerationRunStage}. */
export type ContentGenerationRunStageFilter =
  | "precheck"
  | "llm"
  | "validate"
  | "persist";

export type ContentGenerationRunDb = {
  contentGenerationRun: Pick<
    typeof mediapulsePrisma.contentGenerationRun,
    "create" | "findMany"
  >;
};

/**
 * Persists one content-generation diagnostic run.
 * `id` and `createdAt` are generated by the database.
 *
 * @param data - Validated POST body from the content-generation agent.
 * @param deps - Injectable database dependency (defaults to production Prisma client).
 * @returns The newly created row.
 */
export async function createContentGenerationRun(
  data: {
    agentId: string;
    agentVersion: string;
    tickerId: string;
    outcome: ContentGenerationRunOutcomeFilter;
    stage?: ContentGenerationRunStageFilter | null;
    errorCode?: string | null;
    errorCategory?: string | null;
    message?: string | null;
    durationMs?: number | null;
    pipelineRunId?: string | null;
    executionId?: string | null;
    newsletterId?: string | null;
  },
  deps?: { db?: ContentGenerationRunDb },
) {
  const db = deps?.db ?? mediapulsePrisma;

  const createArgs = {
    data: {
      agentId: data.agentId,
      agentVersion: data.agentVersion,
      tickerId: data.tickerId,
      outcome: data.outcome,
      stage: data.stage ?? null,
      errorCode: data.errorCode ?? null,
      errorCategory: data.errorCategory ?? null,
      message: data.message ?? null,
      durationMs: data.durationMs ?? null,
      pipelineRunId: data.pipelineRunId ?? null,
      executionId: data.executionId ?? null,
      newsletterId: data.newsletterId ?? null,
    },
  } satisfies Prisma.ContentGenerationRunCreateArgs;

  return db.contentGenerationRun.create(createArgs);
}

/**
 * Lists content-generation diagnostic runs newest-first with optional filters.
 * `startTime` / `endTime` filter `createdAt` with `gte` / `lte` independently when provided.
 *
 * @param query - Filter fields from the agent-data-api contract.
 * @param deps - Injectable database dependency (defaults to production Prisma client).
 * @returns Rows ordered newest first.
 */
export async function listContentGenerationRuns(
  query: {
    cursor?: string;
    limit?: number;
    tickerId?: string;
    outcome?: ContentGenerationRunOutcomeFilter;
    startTime?: Date;
    endTime?: Date;
  },
  deps?: { db?: ContentGenerationRunDb },
) {
  const db = deps?.db ?? mediapulsePrisma;

  const createdAtFilter =
    query.startTime !== undefined || query.endTime !== undefined
      ? {
          createdAt: {
            ...(query.startTime !== undefined ? { gte: query.startTime } : {}),
            ...(query.endTime !== undefined ? { lte: query.endTime } : {}),
          },
        }
      : {};

  const where = {
    ...(query.tickerId !== undefined ? { tickerId: query.tickerId } : {}),
    ...(query.outcome !== undefined ? { outcome: query.outcome } : {}),
    ...createdAtFilter,
  } satisfies Prisma.ContentGenerationRunWhereInput;

  const limit = query.limit ?? 50;

  const findManyArgs = {
    where,
    take: limit + 1,
    ...(query.cursor !== undefined
      ? { cursor: { id: query.cursor }, skip: 1 }
      : {}),
    orderBy: { createdAt: "desc" as const },
  } satisfies Prisma.ContentGenerationRunFindManyArgs;

  const rows = await db.contentGenerationRun.findMany(findManyArgs);
  let nextCursor: string | undefined;
  if (rows.length > limit) {
    rows.pop();
    nextCursor = rows[rows.length - 1]?.id;
  }

  return { data: rows, nextCursor };
}
