import { prisma } from "@mediapulse/database";
import { logger } from "@workspace/logger";
import type { PostContentGenerationBody } from "@workspace/agent-data-api-contract";

import type { Prisma } from "@mediapulse/database";

type DataSourceWithScore = Prisma.DataSourceGetPayload<{
  include: {
    articleRelevances: {
      select: {
        score: true;
      };
    };
  };
}>;

type ContentGenerationDb = {
  dataSource: Pick<typeof prisma.dataSource, "findMany">;
  newsletter: Pick<typeof prisma.newsletter, "create" | "findFirst">;
};

/**
 * Returns today's selected data sources for a ticker ordered by relevance score.
 *
 * @param tickerId - Ticker id used to scope data sources and relevance rows.
 * @param deps - Optional dependencies for database and current time.
 * @returns Data sources filtered to selected article relevance rows scored today (UTC).
 */
export const getDataSourcesForTicker = async (
  tickerId: string,
  deps: {
    db?: Pick<ContentGenerationDb, "dataSource">;
    now?: () => Date;
  } = {},
) => {
  const { db = prisma, now = () => new Date() } = deps;
  const startOfTodayUtc = now();
  startOfTodayUtc.setUTCHours(0, 0, 0, 0);

  const queryArgs = {
    where: {
      tickerId,
      articleRelevances: {
        some: {
          tickerId,
          selected: true,
          scoredAt: { gte: startOfTodayUtc },
        },
      },
    },
    include: {
      articleRelevances: {
        where: {
          tickerId,
          selected: true,
          scoredAt: { gte: startOfTodayUtc },
        },
        select: {
          score: true,
        },
      },
    },
    orderBy: {
      createdAt: "desc",
    },
  } satisfies Prisma.DataSourceFindManyArgs;
  const dataSourcesWithScores = await db.dataSource.findMany(queryArgs);

  return dataSourcesWithScores
    .sort((left: DataSourceWithScore, right: DataSourceWithScore) => {
      const leftScore = left.articleRelevances[0]?.score ?? 0;
      const rightScore = right.articleRelevances[0]?.score ?? 0;
      return rightScore - leftScore;
    })
    .map(
      ({
        articleRelevances: _articleRelevances,
        ...dataSource
      }: DataSourceWithScore) => dataSource,
    );
};

/**
 * Creates a newsletter row generated by the content-generation agent.
 *
 * @param data - Newsletter payload received from content-generation.
 * @param db - Database dependency, injectable for tests.
 * @returns Created newsletter record.
 */
export const createNewsletter = async (
  data: PostContentGenerationBody,
  db: Pick<ContentGenerationDb, "newsletter"> = prisma,
) => {
  const newsletter = await db.newsletter.create({
    data: {
      subject: data.subject,
      description: data.description ?? null,
      content: data.content,
      tickerId: data.tickerId,
    },
  });
  logger.info(
    { tickerId: data.tickerId, newsletterId: newsletter.id },
    "Created newsletter for ticker",
  );
  return newsletter;
};

/**
 * Checks whether a newsletter already exists for a given ticker within a
 * specified time window.
 *
 * Used by the content-generation agent skip-if-fresh precheck (MP-CGA-006).
 *
 * @param tickerId - Ticker id to match.
 * @param windowStart - Start of the time window (inclusive, ISO datetime string).
 * @param windowEnd - End of the time window (exclusive, ISO datetime string).
 * @param db - Database dependency, injectable for tests.
 * @returns Object with `hasNewsletter` flag and optional `newsletterId`.
 */
export const getLatestNewsletter = async (
  tickerId: string,
  windowStart: string,
  windowEnd: string,
  db: Pick<ContentGenerationDb, "newsletter"> = prisma,
): Promise<{ hasNewsletter: boolean; newsletterId: string | null }> => {
  const newsletter = await db.newsletter.findFirst({
    where: {
      tickerId,
      createdAt: {
        gte: new Date(windowStart),
        lt: new Date(windowEnd),
      },
    },
    select: { id: true },
    orderBy: { createdAt: "desc" },
  });

  return {
    hasNewsletter: newsletter !== null,
    newsletterId: newsletter?.id ?? null,
  };
};
