import { prisma as mediapulsePrisma } from "@mediapulse/database";
import type { Prisma } from "@mediapulse/database";
import type { QueryDecision } from "@workspace/agent-data-api-contract";

export type QueryAnalysisRunDb = {
  queryAnalysisRun: Pick<typeof mediapulsePrisma.queryAnalysisRun, "create">;
};

/**
 * Persists one query-analysis chronicle run (the per-query decision log).
 * `id` and `createdAt` are generated by the database.
 *
 * @param data - Validated POST body from the query-analysis agent.
 * @param deps - Injectable database dependency (defaults to production Prisma client).
 * @returns The newly created row.
 */
export async function createQueryAnalysisRun(
  data: {
    tickerId: string;
    executionId?: string | null;
    queries: QueryDecision[];
  },
  deps?: { db?: QueryAnalysisRunDb },
) {
  const db = deps?.db ?? mediapulsePrisma;

  const createArgs = {
    data: {
      tickerId: data.tickerId,
      executionId: data.executionId ?? null,
      queries: data.queries as unknown as Prisma.InputJsonValue,
    },
  } satisfies Prisma.QueryAnalysisRunCreateArgs;

  return db.queryAnalysisRun.create(createArgs);
}
