import { describe, expect, it, vi } from "vitest";

import { findActiveQuerySetForNewsletter } from "./active-query-set";

describe("findActiveQuerySetForNewsletter", () => {
  it("resolves the point-in-time set without filtering on the current active flag", async () => {
    const findFirst = vi.fn().mockResolvedValue(null);

    const result = await findActiveQuerySetForNewsletter(
      "ticker-1",
      new Date("2026-05-14T12:00:00.000Z"),
      { searchQuerySet: { findFirst } },
    );

    expect(result).toBeNull();
    expect(findFirst).toHaveBeenCalledTimes(1);
    const args = findFirst.mock.calls[0]?.[0];
    expect(args).toMatchObject({
      where: {
        tickerId: "ticker-1",
        generatedAt: { lte: new Date("2026-05-14T12:00:00.000Z") },
      },
      orderBy: { generatedAt: "desc" },
    });
    expect(args?.where?.isActive).toBeUndefined();
  });

  it("maps queries and labels an agent-generated set with its version", async () => {
    const generatedAt = new Date("2026-05-13T08:00:00.000Z");
    const findFirst = vi.fn().mockResolvedValue({
      id: "set-1",
      generatedAt,
      generationSource: "self_driving_v1",
      agentId: "query-analysis",
      agentVersion: "3.0.0",
      searchQueries: [],
    });

    const result = await findActiveQuerySetForNewsletter(
      "ticker-1",
      new Date("2026-05-14T12:00:00.000Z"),
      { searchQuerySet: { findFirst } },
    );

    expect(result).toStrictEqual({
      setId: "set-1",
      generatedAt: generatedAt.toISOString(),
      generationSource: "self_driving_v1",
      provenanceLabel: "Generated by query-analysis agent (3.0.0)",
      queries: [],
    });
  });

  it("omits the version in the label when the set has no recorded agent version", async () => {
    const findFirst = vi.fn().mockResolvedValue({
      id: "set-1",
      generatedAt: new Date("2026-05-13T08:00:00.000Z"),
      generationSource: "manual_strategy",
      agentId: null,
      agentVersion: null,
      searchQueries: [],
    });

    const result = await findActiveQuerySetForNewsletter(
      "ticker-1",
      new Date("2026-05-14T12:00:00.000Z"),
      { searchQuerySet: { findFirst } },
    );

    expect(result?.provenanceLabel).toBe("Generated by query-analysis agent");
  });

  it("returns queries in rank ascending order from Prisma", async () => {
    const generatedAt = new Date("2026-05-13T08:00:00.000Z");
    const findFirst = vi.fn().mockResolvedValue({
      id: "set-2",
      generatedAt,
      generationSource: "agent_generated",
      searchQueries: [
        {
          id: "q1",
          text: "first query",
          intent: "breaking",
          rank: 1,
        },
        {
          id: "q2",
          text: "second query",
          intent: "thematic",
          rank: 2,
        },
      ],
    });

    const result = await findActiveQuerySetForNewsletter(
      "ticker-1",
      new Date("2026-05-14T12:00:00.000Z"),
      { searchQuerySet: { findFirst } },
    );

    expect(result?.queries.map((q) => q.id)).toStrictEqual(["q1", "q2"]);
    expect(result?.queries[0]).toMatchObject({
      intent: "breaking",
      rank: 1,
    });
  });
});
