import type { Prisma, prisma } from "@mediapulse/database";

/** Shape of one active-query-set entry exposed by the detail handler. */
export type ActiveQuerySetPayload = {
  setId: string;
  generatedAt: string;
  generationSource: string;
  provenanceLabel: string;
  queries: Array<{
    id: string;
    text: string;
    intent: string;
    rank: number;
  }>;
} | null;

/** Prisma collaborator surface for {@link findActiveQuerySetForNewsletter}. */
type SearchQuerySetDelegate = Pick<typeof prisma.searchQuerySet, "findFirst">;

/**
 * Finds the SearchQuerySet that was active when the newsletter was generated: the most recent set
 * generated on or before the newsletter's `createdAt`, regardless of the current `isActive` flag.
 * This is a point-in-time snapshot, so a later query-analysis run that activates a new set does not
 * change what an old newsletter shows. Returns `null` when no set predates the newsletter.
 *
 * @param tickerId - Ticker the newsletter belongs to.
 * @param createdAt - Newsletter's `createdAt` (acts as upper bound for `generatedAt`).
 * @param deps - Prisma `searchQuerySet` delegate (defaults to the global client when wired by the route).
 * @returns The set that was active at generation time with its queries, or `null`.
 */
export const findActiveQuerySetForNewsletter = async (
  tickerId: string,
  createdAt: Date,
  deps: { searchQuerySet: SearchQuerySetDelegate },
): Promise<ActiveQuerySetPayload> => {
  const findFirstArgs = {
    where: {
      tickerId,
      generatedAt: { lte: createdAt },
    },
    include: {
      searchQueries: {
        orderBy: [{ rank: "asc" as const }, { createdAt: "asc" as const }],
      },
    },
    orderBy: { generatedAt: "desc" as const },
  } satisfies Prisma.SearchQuerySetFindFirstArgs;

  const set = await deps.searchQuerySet.findFirst(findFirstArgs);
  if (!set) {
    return null;
  }

  const agentName = set.agentId ?? "query-analysis";
  const provenanceLabel = set.agentVersion
    ? `Generated by ${agentName} agent (${set.agentVersion})`
    : `Generated by ${agentName} agent`;

  return {
    setId: set.id,
    generatedAt: set.generatedAt.toISOString(),
    generationSource: set.generationSource,
    provenanceLabel,
    queries: set.searchQueries.map((query) => ({
      id: query.id,
      text: query.text,
      intent: query.intent,
      rank: query.rank,
    })),
  };
};
