// This file is automatically generated by [env-to-t3 CLI](https://github.com/nicnocquee/env-to-t3)

import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    PORT: z.number({ coerce: true }).optional(),
    AGENT_AUTH_API_URL: z.string().min(1),
    ALLOW_ANY_BEARER_FOR_LOCAL: z.string().default("false").optional(),
    AGENT_REGISTRY_URL: z.string().min(1),
    AGENT_PUBLIC_URL: z.string().min(1),
    DOMAIN_INTEGRATION_API_KEY: z.string().min(1),
    DOMAIN_INTEGRATION_ID: z.string().min(1),
  },
  client: {
  },
  experimental__runtimeEnv: {
  }
});
