// This file is automatically generated by [env-to-t3 CLI](https://github.com/nicnocquee/env-to-t3)

import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    PORT: z.number({ coerce: true }).optional(),
    AGENT_DATA_API_URL: z.string().min(1),
    AGENT_AUTH_API_URL: z.string().min(1),
    AGENT_REGISTRY_URL: z.string().min(1),
    AGENT_PUBLIC_URL: z.string().min(1),
    DOMAIN_INTEGRATION_API_KEY: z.string().min(1),
    DOMAIN_INTEGRATION_ID: z.string().min(1),
    OUTLOOK_CLIENT_ID: z.string().optional(),
    OUTLOOK_CLIENT_SECRET: z.string().optional(),
    OUTLOOK_TENANT_ID: z.string().optional(),
    OUTLOOK_USER_ID: z.string().optional(),
  },
  client: {
    NEXT_PUBLIC_REGISTRATION_EMAIL: z.string().min(1),
  },
  experimental__runtimeEnv: {
    // eslint-disable-next-line strict-env/no-process-env -- env definition file; t3-env requires direct process.env for NEXT_PUBLIC_ vars
    NEXT_PUBLIC_REGISTRATION_EMAIL: process.env.NEXT_PUBLIC_REGISTRATION_EMAIL,
  }
});
