// This file is automatically generated by [env-to-t3 CLI](https://github.com/nicnocquee/env-to-t3)

import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    PORT: z.number({ coerce: true }).optional(),
    AGENT_DATA_API_URL: z.string().min(1),
    AGENT_AUTH_API_URL: z.string().min(1),
    AGENT_REGISTRY_URL: z.string().min(1),
    AGENT_PUBLIC_URL: z.string().min(1),
    DOMAIN_INTEGRATION_API_KEY: z.string().min(1),
    DOMAIN_INTEGRATION_ID: z.string().min(1),
    OPENAI_API_KEY: z.string().min(1),
    OPENAI_MODEL: z.string().min(1),
    QUERY_ANALYSIS_QUERY_COUNT: z.number({ coerce: true }).optional(),
    QUERY_ANALYSIS_ALLOWED_LANGUAGES: z.string().min(1),
    QUERY_ANALYSIS_MIN_DETERMINISTIC_COUNT: z.number({ coerce: true }).optional(),
    QUERY_ANALYSIS_WEIGHT_BREAKING: z.number({ coerce: true }).optional(),
    QUERY_ANALYSIS_WEIGHT_KG_CHANGE: z.number({ coerce: true }).optional(),
    QUERY_ANALYSIS_WEIGHT_FUNDAMENTAL: z.number({ coerce: true }).optional(),
    QUERY_ANALYSIS_MODEL: z.string().min(1),
    QUERY_ANALYSIS_MAX_TOKENS: z.number({ coerce: true }).optional(),
  },
  client: {
  },
  experimental__runtimeEnv: {
  }
});
