// This file is automatically generated by [env-to-t3 CLI](https://github.com/nicnocquee/env-to-t3)

import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    PORT: z.string().optional(),
    AGENT_DATA_API_URL: z.string().optional(),
    AGENT_AUTH_API_URL: z.string().optional(),
    AGENT_REGISTRY_URL: z.string().optional(),
    AGENT_PUBLIC_URL: z.string().optional(),
    DOMAIN_INTEGRATION_API_KEY: z.string().optional(),
    DOMAIN_INTEGRATION_KEY: z.string().optional(),
    RESEND_SENDER: z.string().optional(),
    RESEND_API_KEY: z.string().optional(),
    OUTLOOK_CLIENT_ID: z.string().optional(),
    OUTLOOK_CLIENT_SECRET: z.string().optional(),
    OUTLOOK_TENANT_ID: z.string().optional(),
    OUTLOOK_USER_ID: z.string().optional(),
  },
  client: {
  },
  experimental__runtimeEnv: {
  }
});
