// This file is automatically generated by [env-to-t3 CLI](https://github.com/nicnocquee/env-to-t3)

import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    NODE_ENV: z.string().optional(),
    PORT: z.number({ coerce: true }).optional(),
    AGENT_DATA_API_URL: z.string().min(1),
    REGISTRATION_CONFIRM_SECRET: z.string().min(1),
    USER_REGISTRATION_RESEND_API_KEY: z.string().min(1),
    USER_REGISTRATION_RESEND_FROM: z.string().min(1),
    USER_REGISTRATION_PUBLIC_URL: z.string().min(1),
  },
  client: {
    NEXT_PUBLIC_REGISTRATION_EMAIL: z.string().min(1),
  },
  experimental__runtimeEnv: {
    NEXT_PUBLIC_REGISTRATION_EMAIL: process.env.NEXT_PUBLIC_REGISTRATION_EMAIL,
  }
});
