// This file is automatically generated by [env-to-t3 CLI](https://github.com/nicnocquee/env-to-t3)

import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    PORT: z.number({ coerce: true }).optional(),
  },
  client: {
    NEXT_PUBLIC_REGISTRATION_EMAIL: z.string().min(1),
  },
  experimental__runtimeEnv: {
    NEXT_PUBLIC_REGISTRATION_EMAIL: process.env.NEXT_PUBLIC_REGISTRATION_EMAIL,
  }
});
