// This file is automatically generated by [env-to-t3 CLI](https://github.com/nicnocquee/env-to-t3)

import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    MEDIAPULSE_DATABASE_URL: z.string().min(1),
    HERMES_DATA_SOURCE_MAX_TAKE: z.number({ coerce: true }).optional(),
    MEDIAPULSE_API_URL: z.string().optional(),
    HERMES_API_URL: z.string().optional(),
    DOMAIN_INTEGRATION_API_KEY: z.string().min(1),
    DOMAIN_INTEGRATION_ID: z.string().min(1),
    DOMAIN_INTEGRATION_NAME: z.string().optional(),
    DOMAIN_INTEGRATION_VERSION: z.string().optional(),
    DATABASE_CERT_BASE64: z.string().optional(),
    PORT: z.number({ coerce: true }).optional(),
    AGENT_AUTH_API_URL: z.string().min(1),
    OUTLOOK_CLIENT_ID: z.string().optional(),
    OUTLOOK_CLIENT_SECRET: z.string().optional(),
    OUTLOOK_TENANT_ID: z.string().optional(),
    OUTLOOK_USER_ID: z.string().optional(),
  },
  client: {
  },
  experimental__runtimeEnv: {
  }
});
