// This file is automatically generated by [env-to-t3 CLI](https://github.com/nicnocquee/env-to-t3)

import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    MEDIAPULSE_DATABASE_URL: z.string().min(1),
    HERMES_DATA_SOURCE_MAX_TAKE: z.coerce.number().optional(),
    MEDIAPULSE_API_URL: z.string().min(1),
    HERMES_API_URL: z.string().min(1),
    DOMAIN_INTEGRATION_API_KEY: z.string().min(1),
    DOMAIN_INTEGRATION_ID: z.string().min(1),
    DOMAIN_INTEGRATION_NAME: z.string().optional(),
    DOMAIN_INTEGRATION_VERSION: z.string().optional(),
    DATABASE_CERT_BASE64: z.string().optional(),
    PORT: z.coerce.number().optional(),
    AGENT_AUTH_API_URL: z.string().min(1),
    UNSUBSCRIBE_SECRET: z.string().min(1),
    REGISTRATION_CONFIRM_SECRET: z.string().min(1),
    AGENT_DATA_API_URL: z.string().optional(),
    MEDIAPULSE_CGA_DIAGNOSTICS_ENABLED: z.string().optional(),
    MEDIAPULSE_DAY1_BOOTSTRAP_TRIGGER_ID: z.string().optional(),
    MEDIAPULSE_DAY1_BOOTSTRAP_TRIGGER_TOKEN: z.string().optional(),
    MEDIAPULSE_DAY1_LATEST_ISSUE_TRIGGER_ID: z.string().optional(),
    MEDIAPULSE_DAY1_LATEST_ISSUE_TRIGGER_TOKEN: z.string().optional(),
    MEDIAPULSE_DAY1_TRIGGER_TIMEOUT_MS: z.coerce.number().optional(),
    MEDIAPULSE_DAY1_LATEST_ISSUE_MAX_AGE_HOURS: z.coerce.number().optional(),
    MEDIAPULSE_DAY1_BOOTSTRAP_DEDUPE_MINUTES: z.coerce.number().optional(),
  },
  client: {
  },
  experimental__runtimeEnv: {
  }
});
