// This file is automatically generated by [env-to-t3 CLI](https://github.com/nicnocquee/env-to-t3)

import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    OUTLOOK_CLIENT_ID: z.string().optional(),
    OUTLOOK_CLIENT_SECRET: z.string().optional(),
    OUTLOOK_TENANT_ID: z.string().optional(),
    OUTLOOK_USER_ID: z.string().optional(),
  },
  client: {
  },
  experimental__runtimeEnv: {
  }
});
