// This file is automatically generated by [env-to-t3 CLI](https://github.com/nicnocquee/env-to-t3)

import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    NODE_ENV: z.string().optional(),
    ORCHESTRATION_DATABASE_URL: z.string().min(1),
    HERMES_DATA_SOURCE_MAX_TAKE: z.number({ coerce: true }).optional(),
    DATABASE_CERT_BASE64: z.string().optional(),
    PG_DATAQUEUE_DATABASE: z.string().min(1),
    HERMES_INTERNAL_API_KEY: z.string().min(1),
    HERMES_INTERNAL_API_KEY_PREVIOUS: z.string().optional(),
    AGENT_AUTH_API_URL: z.string().min(1),
    REQUIRE_HTTPS_AGENT_ENDPOINTS: z.string().optional(),
    PROCESSOR_BATCH_SIZE: z.string().optional(),
    PROCESSOR_CONCURRENCY: z.string().optional(),
    HERMES_INVOKE_AGENT_MAX_ATTEMPTS: z.string().optional(),
    HERMES_INVOKE_AGENT_DLQ_JOB_TYPE: z.string().optional(),
    HERMES_INVOKE_AGENT_RETRY_DELAY: z.string().optional(),
    HERMES_INVOKE_AGENT_RETRY_BACKOFF: z.string().optional(),
    HERMES_INVOKE_AGENT_RETRY_DELAY_MAX: z.string().optional(),
  },
  client: {
  },
  experimental__runtimeEnv: {
  }
});
