// This file is automatically generated by [env-to-t3 CLI](https://github.com/nicnocquee/env-to-t3)

import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    DATABASE_URL: z.string().min(1),
    ORCHESTRATION_DATABASE_URL: z.string().optional(),
    HERMES_DATA_SOURCE_MAX_TAKE: z.number({ coerce: true }).optional(),
    MEDIAPULSE_API_URL: z.string().optional(),
    DOMAIN_INTEGRATION_AUTH_TOKEN: z.string().optional(),
    DATABASE_CERT_BASE64: z.string().optional(),
    PG_DATAQUEUE_DATABASE: z.string().min(1),
    HERMES_INTERNAL_API_KEY: z.string().min(1),
    AGENT_AUTH_API_URL: z.string().optional(),
    REQUIRE_HTTPS_AGENT_ENDPOINTS: z.string().optional(),
    PROCESSOR_BATCH_SIZE: z.string().optional(),
    PROCESSOR_CONCURRENCY: z.string().optional(),
  },
  client: {
  },
  experimental__runtimeEnv: {
  }
});
