// This file is automatically generated by [env-to-t3 CLI](https://github.com/nicnocquee/env-to-t3)

import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    ORCHESTRATION_DATABASE_URL: z.string().min(1),
    DATABASE_URL: z.string().optional(),
    HERMES_DATA_SOURCE_MAX_TAKE: z.number({ coerce: true }).optional(),
    DOMAIN_INTEGRATION_AUTH_TOKEN: z.string().optional(),
    DATABASE_CERT_BASE64: z.string().optional(),
    PORT: z.number({ coerce: true }).optional(),
    AGENT_AUTH_API_URL: z.string().optional(),
    HERMES_INTERNAL_API_KEY: z.string().min(1),
    AGENT_AUTH_JWT_SECRET: z.string().optional(),
    TEMP_ADMIN_USERNAME: z.string().min(1),
    TEMP_ADMIN_PASSWORD: z.string().min(1),
  },
  client: {
  },
  experimental__runtimeEnv: {
  }
});
