// This file is automatically generated by [env-to-t3 CLI](https://github.com/nicnocquee/env-to-t3)

import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    ORCHESTRATION_DATABASE_URL: z.string().min(1),
    PG_DATAQUEUE_DATABASE: z.string().optional(),
    HERMES_DATA_SOURCE_MAX_TAKE: z.number({ coerce: true }).optional(),
    DATABASE_CERT_BASE64: z.string().optional(),
    PORT: z.number({ coerce: true }).optional(),
    AGENT_AUTH_API_URL: z.string().optional(),
    HERMES_INTERNAL_API_KEY: z.string().min(1),
    HERMES_INTERNAL_API_KEY_PREVIOUS: z.string().optional(),
    AGENT_AUTH_JWT_SECRET: z.string().optional(),
    TEMP_ADMIN_USERNAME: z.string().min(1),
    TEMP_ADMIN_PASSWORD: z.string().min(1),
    HERMES_DASHBOARD_PUBLIC_URL: z.string().min(1).default("http://localhost:3001"),
    HERMES_RESEND_API_KEY: z.string().optional(),
    HERMES_RESEND_FROM: z.string().optional(),
  },
  client: {
  },
  experimental__runtimeEnv: {
  }
});
