// This file is automatically generated by [env-to-t3 CLI](https://github.com/nicnocquee/env-to-t3)

import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    DATABASE_URL: z.string().min(1),
    DATABASE_CERT_BASE64: z.string().optional(),
    LOG_LEVEL: z.enum(["info", "debug", "warn", "error", "trace", "fatal"]).optional().default("info"),
    PG_DATAQUEUE_DATABASE: z.string().min(1),
    OTEL_EXPORTER_OTLP_ENDPOINT: z.string().url().optional().default("http://localhost:4318"),
    OTEL_SERVICE_NAME: z.string().optional().default("hermes-worker"),
  },
  client: {
  },
  experimental__runtimeEnv: {
  }
});
