// This file is automatically generated by [env-to-t3 CLI](https://github.com/nicnocquee/env-to-t3)

import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    DATABASE_URL: z.string().min(1),
    DATABASE_CERT_BASE64: z.string().optional(),
    PG_DATAQUEUE_DATABASE: z.string().min(1),
  },
  client: {
  },
  experimental__runtimeEnv: {
  }
});
