// This file is automatically generated by [env-to-t3 CLI](https://github.com/nicnocquee/env-to-t3)

import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    DATABASE_URL: z.string().min(1),
    DATABASE_CERT_BASE64: z.string().optional(),
    PORT: z.number({ coerce: true }).optional(),
    AGENT_DATA_API_URL: z.string().optional(),
    AGENT_AUTH_API_URL: z.string().optional(),
    AGENT_API_KEY: z.string().optional(),
    AGENT_AUTH_JWT_SECRET: z.string().optional(),
    REQUIRE_HTTPS_AGENT_ENDPOINTS: z.string().optional(),
    TEMP_ADMIN_USERNAME: z.string().min(1),
    TEMP_ADMIN_PASSWORD: z.string().min(1),
    OUTLOOK_CLIENT_ID: z.string().optional(),
    OUTLOOK_CLIENT_SECRET: z.string().optional(),
    OUTLOOK_TENANT_ID: z.string().optional(),
    OUTLOOK_USER_ID: z.string().optional(),
  },
  client: {
  },
  experimental__runtimeEnv: {
  }
});
