import { createAgentApp } from "@workspace/agent-runtime";
import { env } from "@workspace/env/agents-analysis";
import { z } from "zod";
import { run } from "./run";
import {
  DEFAULT_SCORE_WEIGHTS,
  DEFAULT_TRUSTED_DOMAINS,
} from "./score-articles.js";

// InputSchema is the schema for the input of the agent, which will be sent by Hermes to the agent when the agent is invoked
const InputSchema = z.object({
  tickerId: z.string(),
});

// ConfigSchema is the schema for the config of the agent, which will be sent by Hermes to the agent when the agent is invoked
const ConfigSchema = z.object({
  openAiApiKey: z.string().min(1),
  openAiModel: z.string().min(1),
  verbose: z.boolean().optional(),
  weights: z
    .object({
      aliasMatch: z.number().default(DEFAULT_SCORE_WEIGHTS.aliasMatch),
      entityOverlap: z.number().default(DEFAULT_SCORE_WEIGHTS.entityOverlap),
      freshness: z.number().default(DEFAULT_SCORE_WEIGHTS.freshness),
      sourceQuality: z.number().default(DEFAULT_SCORE_WEIGHTS.sourceQuality),
      novelty: z.number().default(DEFAULT_SCORE_WEIGHTS.novelty),
    })
    .default({}),
  maxSelected: z.number().int().positive().default(10),
  minScoreThreshold: z.number().min(0).max(1).default(0.25),
  trustedDomains: z
    .record(z.string(), z.number())
    .default(DEFAULT_TRUSTED_DOMAINS),
});

export type Config = z.input<typeof ConfigSchema>;
export type ResolvedConfig = z.infer<typeof ConfigSchema>;
export type Input = z.infer<typeof InputSchema>;

const app = createAgentApp<
  Input,
  typeof InputSchema,
  Config,
  typeof ConfigSchema
>(
  {
    agentId: "analysis", // this should be stable for the lifetime of the agent
    agentVersion: "1.0.0", // this should be incremented when the agent is updated
    description: "Generated agent. Customize input, config, and run logic.", // Optional description of the agent but recommended for admins to see in the agent registry
    inputSchema: InputSchema,
    configSchema: ConfigSchema,
    run,
  },
  // Options for the agent app
  {
    // Set the environment variables for the agent app for auto registration with the agent registry:
    // AGENT_AUTH_API_URL: URL of the agent-auth-api service used to verify API keys
    // AGENT_REGISTRY_URL: URL of the agent-registry-api service used to register the agent
    // AGENT_REGISTRY_API_KEY: API key for bearer auth when calling the registry. This should be generated by admin in Hermes dashboard.
    // AGENT_PUBLIC_URL: Public URL where this agent is reachable. This will be used by hermes to call the agent.
    authApiUrl: env.AGENT_AUTH_API_URL ?? "",
    autoRegister:
      env.AGENT_REGISTRY_URL &&
      env.AGENT_REGISTRY_API_KEY &&
      env.AGENT_PUBLIC_URL
        ? {
            registryUrl: env.AGENT_REGISTRY_URL,
            apiKey: env.AGENT_REGISTRY_API_KEY,
            agentUrl: env.AGENT_PUBLIC_URL,
          }
        : undefined,
  },
);

// Export the agent app as a default export
export default {
  port: env.PORT ?? 4010,
  fetch: app.fetch,
};
